"""update users models

Revision ID: 82a631277247
Revises: c5fff9a7638b
Create Date: 2023-10-22 08:00:24.079229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a631277247'
down_revision = 'c5fff9a7638b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.Text(), nullable=False))
    op.drop_index('uq_users_name', table_name='users')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_index('uq_users_name', 'users', ['name'], unique=False)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
