"""update users models

Revision ID: fcb7792aefee
Revises: 82a631277247
Create Date: 2023-10-22 08:48:27.978738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb7792aefee'
down_revision = '82a631277247'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
