"""crteate movie list

Revision ID: 21d84b670174
Revises: fcb7792aefee
Create Date: 2023-10-22 08:50:46.939000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d84b670174'
down_revision = 'fcb7792aefee'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('director', sa.Text(), nullable=False),
    sa.Column('genre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movies'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
